### PR TITLE
Feature email styling

### PR DESCRIPTION
**Pull request by mpeck99**
I have started the email styling to make the !verify email look better. Any feedback on things that could be added or changed would be awesome!

### CODE REVIEW

**Comment by brennondenny** [comment]
The template looks great, I was able to receive the verification code no problem. I would try to make the social media links a bit more spaced out but other than that good job.

**Comment by brennondenny** [comment]
Everything looks good now, ready for merge 👍

**Comment by mattpezzente** [comment]
Nice update to the email message overall! Everything worked well on my end, no issues from what I could see.

**Review by mattpezzente — CHANGES_REQUESTED** [review]
Please remove your welcome.js controller and any welcome functionality from the final build, UNLESS it is agreed to be added as a new command to the Release3.

**Review by mattpezzente — APPROVED** [review]

**Pull request closed without merging**
